---
# dnf_repo_sync defaults

# 是否在同步前暂时禁用系统所有 yum 源
# 强烈建议开启，防止 reposync 使用机器上已安装的 repo 导致同步错误内容
dnf_repo_sync_disable_system_repos: true

# 以下是其他默认值

dnf_repo_sync_base_path: /var/www/html/repos
dnf_repo_sync_repo_owner: root
dnf_repo_sync_repo_group: root

dnf_repo_sync_sources: {}

dnf_repo_sync_auto_update: false
dnf_repo_sync_cron_minute: "0"
dnf_repo_sync_cron_hour: "3"
dnf_repo_sync_cron_day: "*"
dnf_repo_sync_cron_month: "*"
dnf_repo_sync_cron_weekday: "*"
dnf_repo_sync_cron_job_name: "update-dnf-repos"

dnf_repo_sync_clean: false
dnf_repo_sync_state: present
dnf_repo_sync_reposync_options: "--download-metadata --downloadcomps --delete --newest-only"
dnf_repo_sync_serve_repos: true
dnf_repo_sync_web_server: nginx
dnf_repo_sync_manage_firewall: true
dnf_repo_sync_firewall_ports:
  - "80/tcp"
  - "443/tcp"
dnf_repo_sync_manage_selinux: true
